baseURL = "http://www.heirbaut.nl/"
languageCode = "en-us"
title = "Niels' Homepage"
theme = "ananke"

[params]
  featured_image = "/images/fernando-hernandez-JdoofvUDUwc-unsplash.jpg"
    github = "https://github.com/nheirbaut/"
    linkedin = "https://www.linkedin.com/in/nielsheirbaut/"